import type { VercelRequest, VercelResponse } from '@vercel/node';
import { GoogleGenAI } from '@google/genai';

// This function runs on the server, keeping the API key secure.
function getAiClient(): GoogleGenAI {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
  }
  return new GoogleGenAI({ apiKey: process.env.API_KEY });
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', ['POST']);
    return res.status(405).end('Method Not Allowed');
  }

  try {
    const { prompt } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: 'Missing prompt in request body.' });
    }

    const client = getAiClient();
    
    // Using gemini-2.5-flash-image for generation
    const response = await client.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts: [{ text: prompt }] }
      // Removed responseMimeType to prevent generation errors
    });

    let generatedImage = null;

    if (response.candidates?.[0]?.content?.parts) {
       for (const part of response.candidates[0].content.parts) {
         if (part.inlineData) {
           generatedImage = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
           break;
         }
       }
    }

    if (!generatedImage) {
        throw new Error("No image generated by the model.");
    }

    res.status(200).json({ generatedImage });

  } catch (error: any) {
    console.error('API Error in /api/generate-style:', error);
    res.status(500).json({ error: 'Failed to generate style preview.', details: error.message });
  }
}