import type { VercelRequest, VercelResponse } from '@vercel/node';
import { GoogleGenAI } from '@google/genai';

function getAiClient(apiKey: string): GoogleGenAI {
  return new GoogleGenAI({ apiKey });
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', ['POST']);
    return res.status(405).end('Method Not Allowed');
  }

  try {
    const { prompt, apiKey } = req.body;

    if (!prompt) {
      return res.status(400).json({ error: 'Missing prompt in request body.' });
    }

    const keyToUse = apiKey || process.env.API_KEY;

    if (!keyToUse) {
      return res.status(401).json({ 
        error: 'No API Key available.', 
        details: 'System is missing API Key configuration.' 
      });
    }

    const client = getAiClient(keyToUse);

    // Using gemini-3-pro-image-preview for High Quality
    const response = await client.models.generateContent({
        model: 'gemini-3-pro-image-preview',
        contents: { parts: [{ text: `Professional portrait photography, 8k resolution, highly detailed, photorealistic. ${prompt}` }] },
        config: {
            imageConfig: {
                aspectRatio: '1:1',
                imageSize: '1K'
            }
        }
    });

    let finalImage = null;
    if (response.candidates?.[0]?.content?.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                finalImage = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
                break;
            }
        }
    }

    if (!finalImage) {
        throw new Error("No image generated by Gemini model.");
    }

    res.status(200).json({ finalImage });

  } catch (error: any) {
    console.error('API Error in /api/generate-final-image:', error);
    res.status(500).json({ error: 'Failed to generate the final image.', details: error.message });
  }
}